export const DEFAULT_MANA_INCREASE = 1
export const MAX_MANA_CAPACITY = 12

export const ACTION_DIE_SKIP_ATTACKS = 1
export const ACTION_DIE_ONE_CARD = 2
export const ACTION_DIE_MINIMUM_ATTACK = 3
export const ACTION_DIE_MINIMUM_ATTACK_VALUE = 3
export const ACTION_DIE_EXTRA_CARD = 4
export const ACTION_DIE_MANA_DISCOUNT = 5
export const ACTION_DIE_LESS_MANA_COST = 1
export const ACTION_DIE_DOUBLE_DAMAGE = 6
export const FATE_DIE_MISS_CHANCE = 1
export const FATE_DIE_DOUBLE_DAMAGE_CHANCE = 3
export const FATE_DIE_CHAIN_DAMAGE = 4
export const REVERSAL_COIN_TURNS_INTERVAL = 3
export const FAVORABLE_STREAK_MIN_NUMBER = 4

export const CHAOS_DECK_EXHAUSTION_THRESHOLD = 3
export const CHAOS_EARTHQUAKE_DAMAGE = 2
export const CHAOS_BLOOD_MOON_MINIONS_DAMAGE = 1
export const CHAOS_SURGE_ATTACK_BONUS = 2

export const MINOR_RITUAL_ENERGY_THRESHOLD = 8
export const MODERATE_RITUAL_ENERGY_THRESHOLD = 16
export const MAJOR_RITUAL_ENERGY_THRESHOLD = 24
export const GRAND_RITUAL_ENERGY_THRESHOLD = 32
export const MINOR_RITUAL_DAMAGE = 3
export const MODERATE_RITUAL_DAMAGE = 6
export const MAJOR_RITUAL_DAMAGE = 8
export const GRAND_RITUAL_DAMAGE = 10
export const DARK_CONVERGENCE_DAMAGE = 3
export const SOUL_HARVEST_CARDS_COUNT = 3
export const BLOODBIND_HEAL_AMOUNT = 6
export const ASHEN_STRIKE_DAMAGE = 4

export const ECLIPSE_RESET_TURNS_DISCOUNT = 2
export const ECLIPSE_PHASE_DAMAGE = 2
export const ECLIPSE_PHASE_EMPTY_BOARD_DAMAGE = 3
export const ECLIPSE_PHASE_ENTERED_EMPTY_BOARD_DAMAGE = 4
export const ECLIPSE_TIMER_MIN_TURNS = 2